# Qu'est-ce que R ? {#sec-def-r}

<br>

::: {.callout-tip icon="false"}
## R est un langage et un environnement de programmation, initialement développé pour les calculs statistiques et les graphiques[^def-r-1].
:::

[^def-r-1]: [What is R?](https://www.r-project.org/about.html)

R a été écrit à l'origine par Robert Gentlement et Ross Ihaka, tous les deux membres du Département de Statistiques de l'Université d'Auckland[^def-r-2].

[^def-r-2]: [Contributors](https://www.r-project.org/contributors.html)

<br>

::: {.callout-tip icon="true"}
## Quelques dates

|  |  |
|---------------------|---------------------------------------------------|
| 1991 | Création du langage R |
| 1993 | R est dévoilé au public |
| 1996 | [Article dans le *Journal of Computational and Graphical Statistics*](https://www.stat.auckland.ac.nz/~ihaka/downloads/R-paper.pdf) |
:::

<br>

R désigne également le logiciel qui utilise ce langage pour des calculs statistiques (et tout un tas d'autres applications (manipulation de données, graphiques, ...).

Il dispose d'une communauté en ligne très active ainsi que d'extensions appelées **packages** pour presque tous les domaines et applications possibles et imaginables (cartographie, fouille de texte, modélisation, ...).

Contrairement à d'autres logiciels de statistiques comme Minitab ou SPSS, R peut être exécuté entièrement en **ligne de commande** et ne nécessite pas d'interface graphique, ce qui lui confère une grande flexibilité.

<br>

::: {.callout-tip icon="true"}
## Quelques avantages de R

-   C'est un outil libre et open source (tout le monde peut utiliser le code et voir comment il fonctionne)

-   C'est un langage de programmation plutôt qu'une interface graphique, ce qui permet à l'utilisateur de sauvegarder facilement des **scripts** pour les ré-utiliser ou les partager

-   Beaucoup de personnes l'utilisent dans beaucoup de domaines différents - il est rare d'être confronté à un problème qui n'a jamais été résolu !
:::
