# Bienvenue {.unnumbered}

Ce livre regroupe les supports de formations R proposées dans le cadre des **ateliers codons**.

Ces ateliers ont pour but de regrouper les utilisateurs de R au sein d'un laboratoire de recherche lors de sessions de 2 à 3 heures pour découvrir, re-découvrir ou progresser en R.

Ces ateliers sont encadrés par une personne familière avec R et le contenu des supports, avec si nécessaire l'appui de personnes supplémentaires pour aider les participants.

L'idée des ateliers est de "plonger dans le bain" rapidement, sans consacrer trop de temps à des explications théoriques déconnectées de la pratique.

Les explications théoriques seront apportées au fur et à mesure des cas concrets.

L'animation d'un atelier peut se faire de plusieurs manières :

-   projeter sur un écran la session de la personne qui anime l'atelier, pour une démonstration "en live"

-   projeter les diapositives associées au contenu d'un atelier, qui contiennent le code et des questions / exercices
